version: "2"

services:
  app:
    container_name: fikasio-usernews
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/app
