FROM golang:1.19.4

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...
RUN go mod tidy
RUN go install -v ./...
RUN go install -mod=mod github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main
