name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        env:
          AWS_ACCOUNT_IDENTIFIER: ${{ secrets.AWS_ACCOUNT_IDENTIFIER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          IMAGE_URL: ${{ secrets.IMAGE_URL }}
        run: |
          export FUNCTION_NAME=fikasio-usernews
          export VERSION=${{ github.ref_name }}
          export TAG="${VERSION:1}"
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_IDENTIFIER.dkr.ecr.$AWS_REGION.amazonaws.com
          docker build \
            -t $IMAGE_URL:$TAG \
            -t $IMAGE_URL:latest .
          docker push $IMAGE_URL --all-tags
          aws lambda update-function-code --region $AWS_REGION --function-name $FUNCTION_NAME --image-uri $IMAGE_URL:latest
